### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by adligo** [archiecobbs/gwt-lzma#5]
Hi,

   Thanks for doing this work, I know how much of a pain porting compression libraries can be;
http://cvs.adligo.org/viewvc/jme_zip_cache/

   The gwt-lzma project does NOT have a license?  I assume your ok with Apache 2.0, if I fork to add a license?  
   I am looking to use gwt-lzma for a fringe Use-Case when documenting adligo.org using addoc.adligo.org. Addoc a article based documentation system with ads to generate revenue from documentation on open source projects.    It's design is pretty simple, host each article as a html files lzma compressed files so that the web crawlers don't display the individual articles (like they do with apache ant documentation).  In the GWT addoc app decompress the files and display them when a user clicks on a menu selection (similar a the git doc but with adds).
https://git-scm.com/docs/user-manual.html

https://www.google.com/support/enterprise/static/gsa/docs/admin/74/gsa_doc_set/admin_crawl/preparing.html#1077236
http://www.ibm.com/support/knowledgecenter/SS5SQ7_8.5.0/com.ibm.discovery.es.ad.doc/administering/iiysacrawlarchive.htm

   In the future if browser and web crawlers start to treat these as regular files, I will add some simple symmetric (hackable) encryption or something to obfuscate the article content further, when it's not rendered with the menu. 

   I also write a large number of projects on github, I simply add the Apache 2.0 license file without editing each file like the Apache 2.0 license itself specifies to do.   In the future I am hoping to add a command to Fabricate (fabricate.adligo.org) to modify source files adding the license comments in a automated fashion.

Cheers,
Scott

**Comment by archiecobbs** [comment]
Hi Scott,

Thanks for the heads-up. I've added the Apache 2.0 license.
